### PR TITLE
fix: get `is_focused` value dynamically

### LINKED ISSUE #190: Find a way to check if window is focused for long-running apps
@nashaofu although the current solution for checking if the window is focused is good and it works, it does not work for long-running apps such as mediar-ai/screenpipe.

it'd be good to have some way to either:
1. reload the Window state, so we can check if it's focused at the moment
2. make `is_focused` a computed function, which will check against `pid` of _currently_ focused window
3. get the focused `Window` from the `Monitor`

also @louis030195, please share if you can think of any alternative solution

### PR DESCRIPTION
**Pull request by ologbonowiwi**
closes #190

- **feat: write example to test against**
- **feat: use `activeApplication` to get focused app**

### CODE REVIEW

**Comment by ologbonowiwi** [comment]
first execution is on this branch. second execution is on master version @nashaofu @louis030195 

https://github.com/user-attachments/assets/7012dec1-c443-41bb-93b0-730460a8eb3d

File: examples/focused_window.rs [hunk 1]
```diff
@@ -0,0 +1,25 @@
+use std::thread;
+use xcap::Window;
+
+fn main() {
+    thread::sleep(std::time::Duration::from_secs(3));
+
+    loop {
+        let windows = Window::all().unwrap();
```
Comment (ologbonowiwi) [inline examples/focused_window.rs:8]: we have the issue that here we recreate all windows every time, which IDK if it's what screenpipe does. if we put this creation outside of the loop, we get a freezed version same as master version

File: src/window.rs [hunk 2]
```diff
@@ -76,7 +76,7 @@ impl Window {
     }
     /// The window is focused.
     pub fn is_focused(&self) -> bool {
-        self.impl_window.is_focused
+        self.impl_window.is_focused()
```
Comment (ologbonowiwi) [inline src/window.rs:79]: If we don't get the value from a function, we get the focused app when the `Window` has been built. now we get if the value is focused at the time of checking instead of a static value

File: examples/focused_window.rs (hunk 1 above)
Comment (ologbonowiwi) [reply examples/focused_window.rs]: fixed by the computed function

**Comment by louis030195** [comment]
nice

File: examples/focused_window.rs (hunk 1 above)
Comment (nashaofu) [reply examples/focused_window.rs]: Later, I will consider transforming all attributes into functional forms.

**Review by nashaofu — APPROVED** [review]
